name: pekerjaan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  google_sign_in: ^5.2.1
  get_storage: ^2.0.3
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  clipboard: ^0.1.3
  intl: ^0.17.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  animate_do: ^2.1.0 
  glass: ^1.0.1+1
  
  
  
dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.1.7
  hive_generator: ^1.1.2

flutter: 
  uses-material-design: true
  assets:
    - assest/
